<a href="https://colab.research.google.com/github/sunitmal/DataAcademySunitMal/blob/main/sunitmalHLTWK3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
# WEEK 3 Numpy TASK 1#

import numpy as np
array=np.arange(0,10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
#WEEK 3 Numpy TASK 2#

import numpy as np

sample_arr = [True]

bool_arr = np.random.choice(sample_arr, size=(3,3))

print('2D Numpy Array: ')
print(bool_arr)



2D Numpy Array: 
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [39]:
#WEEK 3 Numpy TASK 3#

import numpy as np

array=np.arange(10)
result=[]
for i in array:
  if i % 2 == 1:
    result.append(i)
    print(np.array(result))

[1]
[1 3]
[1 3 5]
[1 3 5 7]
[1 3 5 7 9]


In [68]:
#WEEK 3 Numpy TASK 4#

import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9,10])

odd_values=(a%2 == 1)
a[odd_values]=-1
print(a)


[-1  2 -1  4 -1  6 -1  8 -1 10]


In [34]:
#WEEK 3 Numpy TASK 5#

import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr_2d = np.reshape(arr, (2, 5))
print(arr_2d)



[[0 1 2 3 4]
 [5 6 7 8 9]]


In [59]:
#WEEK 3 Numpy TASK 6#

import numpy as np

a = np.arange(1,10)
b = np.arange(10,19)
c = np.dot(a,b)

new_array =  np.vstack((a,b))
print("\nStack arrays in sequence vertically:")
print(new_array)
e = np.sum(c,axis=0)
print(e)


Stack arrays in sequence vertically:
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]
690
